export default {
  fonts: {
    headers: "Poppins, sans-serif",
    headersFallbacks: "Montserrat, sans-serif",
    main: "Poppins, sans-serif",
    mainFallbacks: "Open Sans, sans-serif",
  },
  colors: {
    black: "#212F3D",
    black2: "#000",
    blue: "#2F80ED",
    white: "#fff",
    main1: "hsl(207,70%,59%)",
    main2: "hsl(207,70%,94%)",
    dark1: "hsl(227,2%,12%)",
    dark2: "hsl(227,2%,26%)",
    dark3: "hsl(227,2%,64%)",
    light1: "hsl(0,0%,97%)",
    light2: "hsl(0,0%,99%)",
  },
  breakpoints: {
    mobile: "only screen and (min-width: 425px)",
    tabletPortrait: "only screen and (min-width: 768px)",
    tabletLandscape: "only screen and (min-width: 1024px)",
    desktop: "only screen and (min-width: 1200px)",
    desktopL: "only screen and (min-width: 1440px)",
    desktopXL: "only screen and (min-width: 1600px)",
    desktop2XL: "only screen and (min-width: 1920px)",
  },
  maxWidths: {
    mobile: "425px",
    tabletPortrait: "768px",
    tabletLandscape: "1024px",
    desktop: "1200px",
    desktopL: "1440px",
    desktopXL: "1600px",
    desktop2XL: "1920px",
    desktop3XL: "2200px",
  },
  spacings: {
    base: "16px",
  },
  borderStyles: {
    radius: "calc(var(--base-size) - 10px)",
  },
};
